### ISSUE TITLE
Error from running sample in Visual Studio

### ISSUE THREAD

**Issue by archunz** [Microsoft/Cognitive-Emotion-Windows#19]
[06:11:32.358271]: VisionServiceClient is created
[06:11:32.361272]: Calling VisionServiceClient.DescribeAsync()...
[06:11:32.454657]: Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__42_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__42`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<DescribeAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.DescribePage.<DescribeUrl>d__2.MoveNext() in C:\Users\archba\Desktop\CognitiveVisionWindows\Sample-WPF\DescribePage.xaml.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VisionAPI_WPF_Samples.DescribePage.<DoWork>d__3.MoveNext() in C:\Users\archba\Desktop\CognitiveVisionWindows\Sample-WPF\DescribePage.xaml.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at VisionAPI_WPF_Samples.ImageScenarioPage.<ShowPreviewAndDoWork>d__15.MoveNext() in C:\Users\archba\Desktop\CognitiveVisionWindows\Sample-WPF\ImageScenarioPage.cs:line 90

**Comment by mattryles** [comment]
Also getting this error :(

**Comment by cthrash** [comment]
The exception should contain additional information.  The three most likely issues are:

1) API Key is incorrect or absent
2) API Key does not match the region for which you have access (check the API URL in the Azure portal, and create the `EmotionServiceClient` using the constructor that takes two arguments).
3) Image is invalid or not supported
