### ISSUE TITLE
Exception in emotion detection

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Emotion-Windows#2]
_From @basimolimajeed on July 8, 2016 15:14_

Hi, tried to run the sample for emotion detection on windows 10. The image is loaded then I get this exception:
[16:02:47.891793]: EmotionServiceClient is created
[16:02:47.910295]: Calling EmotionServiceClient.RecognizeAsync()...
[16:02:54.305999]: Microsoft.ProjectOxford.Common.ClientException: Exception of type 'Microsoft.ProjectOxford.Common.ClientException' was thrown.
   at Microsoft.ProjectOxford.Common.ServiceClient.<SendAsync>d__22`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Common.ServiceClient.<PostAsync>d__20`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Emotion.EmotionServiceClient.<RecognizeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Emotion.EmotionServiceClient.<RecognizeAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EmotionAPI_WPF_Samples.DetectEmotionUsingStreamPage.<UploadAndDetectEmotions>d__1.MoveNext() in C:\Users\basim\Source\Repos\ProjectOxford-ClientSDK\Emotion\Windows\Sample-WPF\DetectEmotionUsingStreamPage.xaml.cs:line 113

[16:02:54.336011]: Detection Result:
[16:02:54.346018]: No emotion is detected. This might be due to:
    image is too small to detect faces
    no faces are in the images
    faces poses make it difficult to detect emotions
    or other factors

Any idea why?
Thanks

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#87_

**Comment by VenkatKL** [comment]
Hi,

Even we are also experiencing **Cognitive Emotion** related Issues like; 

**### Exceptioin of type 'Microsoft.ProjectOxford.Common.ClientException'**

Here is the [Print Screen](https://twitter.com/VenkatKL/status/824358653016834048) of the same - [https://twitter.com/VenkatKL/status/824358653016834048](https://twitter.com/VenkatKL/status/824358653016834048)

What Could be the reason? It is bit urgent. Kindly reply.

Thanks & Regards,

**Comment by cthrash** [comment]
There should be additional details in the exception (an Error member).  What does that say?

**Comment by cthrash** [comment]
Closing due to inactivity.
