### ISSUE TITLE
[System.Threading.Tasks.TaskCanceledException: A task was canceled] occured while using the Detect emotion in a video

### ISSUE THREAD

**Issue by lanceptrck** [Microsoft/Cognitive-Emotion-Windows#22]
[12:03:35.598941]: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Common.ServiceClient.<SendAsync>d__22`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Common.ServiceClient.<PostAsync>d__20`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.Emotion.EmotionServiceClient.<RecognizeInVideoAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EmotionAPI_WPF_Samples.EmotionDetectionUsingVideoPage.<UploadAndDetectEmotions>d__5.MoveNext() in C:\OUT\Sample-WPF\EmotionDetectionUsingVideoPage.xaml.cs:line 68

Above is the stack trace

**Comment by cthrash** [comment]
The video methods are no longer supported.
